logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.springframework.web.socket: OFF
    org.springframework.web.socket.server.support: OFF
    org.apache.tomcat.websocket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp.stomp: OFF # TRACE
    org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler: OFF #TRACE
    org.springframework.messaging.simp.stomp.StompSession: OFF # TRACE
    org.springframework.messaging.simp.broker: OFF # DEBUG
    org.springframework.security.web.FilterChainProxy: OFF #DEBUG
    org.springframework.security.web.authentication: OFF #DEBUG
    org.springframework.security.config: OFF #DEBUG

    # OPTIONAL: your custom package if you want to see your own logs
    com.woow: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 7MB
  messaging:
    stomp:
      relay:
        heartbeat:
          send-interval: 10000 # in miliseconds
          receive-interval: 60000
  config:
    import: classpath:banner-config.yml
  flyway:
    enabled: false
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_OPTION}
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  host: ${APP_HOST}
woo:
  bo:
    email:
      mailgun:
        apiKey: 7cd19b69b308b23b8907b2108689e2a5-02fa25a3-ab30a1b8
        user: postmaster@axtrading.io
        pwd: 174c7acda9022896b0911a6f6c43fc3c-02fa25a3-40f876ec
        domain: axtrading.io
    data:
      encryption:
        key: a9f3k7v2x1z8p6q4

sms:
  accountSID: ACb5e031dff028e2577518e3a0eb186780
  authToken: 637c1947732fef8a996eed70f00078a7
  fromTelephoneNumber: +17372381580

mail:
  smtp:
    ssl:
      trust: true

email:
  group: ${EMAIL_GROUP}

server:
  port: ${PORT}
  shutdown: graceful
  forward-headers-strategy: native

google:
  recaptcha:
    key:
      site: 6LeBD2ghAAAAADZG78n8VRzMYlUlGTP2h1Xos93u
      secret: 6LeBD2ghAAAAAIwmqN_EjY0H0vUFcoEPH-mwc8IB
stomp:
  broker:
    relay-host: ${STOMP_BROKER_RELAY_HOST}
    relay-port: ${STOMP_BROKER_RELAY_PORT}
    admin-port: ${STOMP_BROKER_ADMIN_PORT}
    client-login: ${STOMP_BROKER_CLIENT_LOGIN}
    client-passcode: ${STOMP_BROKER_CLIENT_PASSCODE}
    system-login: ${STOMP_BROKER_SYSTEM_LOGIN}
    system-passcode: ${STOMP_BROKER_SYSTEM_PASSCODE}
    max-connections: ${STOMP_BROKER_MAX_CONNECTIONS}
    pending-acquire-max-count: ${STOMP_BROKER_PENDING_ACQUIRE_MAX_COUNT}
    pending-acquire-timeout-in-seconds: ${STOMP_BROKER_PENDING_ACQUIRE_TIMEOUT_IN_SECONDS}
    connection-pool-name: ${STOMP_BROKER_CONNECTION_POOL_NAME}
    heartbeat:
      send-interval: ${STOMP_BROKER_HEARTBEAT_SEND_INTERVAL}
      receive-interval: ${STOMP_BROKER_HEARTBEAT_RECEIVE_INTERVAL}