logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF

    # ADD THESE FOR WEBSOCKET DEBUGGING 👇
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.server.support: DEBUG
    org.apache.tomcat.websocket: DEBUG
    org.springframework.messaging: DEBUG

    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.config: DEBUG

    # OPTIONAL: your custom package if you want to see your own logs
    com.woow: DEBUG

spring:
  messaging:
    stomp:
      relay:
        heartbeat:
          send-interval: 5000 # in miliseconds
          receive-interval: 5000
  config:
    import: classpath:banner-config.yml
  flyway:
    enabled: false
  profiles:
    active: prod
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${DDL_OPTION}
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  host: ${APP_HOST}
woo:
  bo:
    email:
      mailgun:
        apiKey: 7cd19b69b308b23b8907b2108689e2a5-02fa25a3-ab30a1b8
        user: postmaster@axtrading.io
        pwd: 174c7acda9022896b0911a6f6c43fc3c-02fa25a3-40f876ec
        domain: axtrading.io
    data:
      encryption:
        key: a9f3k7v2x1z8p6q4

sms:
  accountSID: ACb5e031dff028e2577518e3a0eb186780
  authToken: 637c1947732fef8a996eed70f00078a7
  fromTelephoneNumber: +17372381580

mail:
  smtp:
    ssl:
      trust: true

email:
  group: ${EMAIL_GROUP}

server:
  port: ${PORT}
  shutdown: graceful
  forward-headers-strategy: native

google:
  recaptcha:
    key:
      site: 6LeBD2ghAAAAADZG78n8VRzMYlUlGTP2h1Xos93u
      secret: 6LeBD2ghAAAAAIwmqN_EjY0H0vUFcoEPH-mwc8IB
stomp:
  broker:
    relay-host: 0rbjt9.stackhero-network.com
    relay-port: 63338
    admin-port: 5909
    client-login: admin
    client-passcode: 9KLwnaP17gIdi8CoDetZIlHMgaaVxkqf
    system-login: admin
    system-passcode: 9KLwnaP17gIdi8CoDetZIlHMgaaVxkqf
    max-connections: 10
    pending-acquire-max-count: -1
    pending-acquire-timeout-in-seconds: 30
    connection-pool-name: rabbitmq-pool
    heartbeat:
      send-interval: 10000  # milliseconds
      receive-interval: 10000